export const players = [
  {
    value: "Креветка",
    label: "Креветка",
    color: "pink",
    status: false,
  },
  {
    value: "Уголь",
    label: "Уголь",
    color: "black",
    status: false,
  },
  {
    value: "Кирпич",
    label: "Кирпич",
    color: "cherry",
    status: false,
  },
  {
    value: "Рябчик",
    label: "Рябчик",
    color: "Brown",
    status: false,
  },
  {
    value: "Лучик",
    label: "Лучик",
    color: "Yellow",
    status: false,
  },
  {
    value: "Малинка",
    label: "Малинка",
    color: "magenta",
    status: false,
  },
  {
    value: "Иней",
    label: "Иней",
    color: "lite blue",
    status: false,
  },
  {
    value: "Томат",
    label: "Томат",
    color: "red",
    status: false,
  },
  {
    value: "Оливка",
    label: "Оливка",
    color: "olive",
    status: false,
  },
  {
    value: "Крокодил",
    label: "Крокодил",
    color: "green",
    status: false,
  },
  {
    value: "Баклажан",
    label: "Баклажан",
    color: "purple",
    status: false,
  },
  {
    value: "Синяк",
    label: "Синяк",
    color: "dark purple",
    status: false,
  },
  {
    value: "Кефир",
    label: "Кефир",
    color: "White",
    status: false,
  },
  {
    value: "Апельсин",
    label: "Апельсин",
    color: "Orange",
    status: false,
  },
  {
    value: "Желток",
    label: "Желток",
    color: "honey",
    status: false,
  },
  {
    value: "Слива",
    label: "Слива",
    color: "blue",
    status: false,
  },
  {
    value: "Голубика",
    label: "Голубика",
    color: "indigo",
    status: false,
  },
];
