export const players = [
  {
    value: 'Креветка',
    label: 'Креветка',
    color: '#eaadab',
    spotColor: '#eaadab',
    status: false,
    votes: 0,
  },
  {
    value: 'Уголь',
    label: 'Уголь',
    color: '#010101',
    spotColor: '#010101',
    status: false,
    votes: 0,
  },
  {
    value: 'Кирпич',
    label: 'Кирпич',
    color: '#851e1f',
    spotColor: '#851e1f',
    status: false,
    votes: 0,
  },
  {
    value: 'Рябчик',
    label: 'Рябчик',
    color: '#772c29',
    spotColor: '#e3ccc0',
    status: false,
    votes: 0,
  },
  {
    value: 'Лучик',
    label: 'Лучик',
    color: '#e5ba5c',
    spotColor: '#e5ba5c',
    status: false,
    votes: 0,
  },
  {
    value: 'Малинка',
    label: 'Малинка',
    color: '#dd3362',
    spotColor: '#dd3362',
    status: false,
    votes: 0,
  },
  {
    value: 'Иней',
    label: 'Иней',
    color: '#b6eeff',
    spotColor: '#b6eeff',
    status: false,
    votes: 0,
  },
  {
    value: 'Томат',
    label: 'Томат',
    color: '#db2a08',
    spotColor: '#db2a08',
    status: false,
    votes: 0,
  },
  {
    value: 'Оливка',
    label: 'Оливка',
    color: '#a1bbb2',
    spotColor: '#a1bbb2',
    status: false,
    votes: 0,
  },
  {
    value: 'Крокодил',
    label: 'Крокодил',
    color: '#7ab849',
    spotColor: '#7ab849',
    status: false,
    votes: 0,
  },
  {
    value: 'Баклажан',
    label: 'Баклажан',
    color: '#735a6f',
    spotColor: '#735a6f',
    status: false,
    votes: 0,
  },
  {
    value: 'Синяк',
    label: 'Синяк',
    color: '#41456b',
    spotColor: '#41456b',
    status: false,
    votes: 0,
  },
  {
    value: 'Кефир',
    label: 'Кефир',
    color: '#ffffff',
    spotColor: '#ffffff',
    status: false,
    votes: 0,
  },
  {
    value: 'Апельсин',
    label: 'Апельсин',
    color: '#ff5c05',
    spotColor: '#ff5c05',
    status: false,
    votes: 0,
  },
  {
    value: 'Желток',
    label: 'Желток',
    color: '#d58e22',
    spotColor: '#d58e22',
    status: false,
    votes: 0,
  },
  {
    value: 'Слива',
    label: 'Слива',
    color: '#3739c0',
    spotColor: '#3739c0',
    status: false,
    votes: 0,
  },
  {
    value: 'Голубика',
    label: 'Голубика',
    color: '#0058b2',
    spotColor: '#0058b2',
    status: false,
    votes: 0,
  },
];
