export const players = [
  {
    value: "Креветка",
    label: "Креветка",
    color: "#eaadab",
    spotColor: "#eaadab",
    status: false,
  },
  {
    value: "Уголь",
    label: "Уголь",
    color: "#010101",
    spotColor: "#010101",
    status: false,
  },
  {
    value: "Кирпич",
    label: "Кирпич",
    color: "#851e1f",
    spotColor: "#851e1f",
    status: false,
  },
  {
    value: "Рябчик",
    label: "Рябчик",
    color: "#772c29",
    spotColor: "#e3ccc0",
    status: false,
  },
  {
    value: "Лучик",
    label: "Лучик",
    color: "#e5ba5c",
    spotColor: "#e5ba5c",
    status: false,
  },
  {
    value: "Малинка",
    label: "Малинка",
    color: "#dd3362",
    spotColor: "#dd3362",
    status: false,
  },
  {
    value: "Иней",
    label: "Иней",
    color: "#b6eeff",
    spotColor: "#b6eeff",
    status: false,
  },
  {
    value: "Томат",
    label: "Томат",
    color: "#db2a08",
    spotColor: "#db2a08",
    status: false,
  },
  {
    value: "Оливка",
    label: "Оливка",
    color: "#a1bbb2",
    spotColor: "#a1bbb2",
    status: false,
  },
  {
    value: "Крокодил",
    label: "Крокодил",
    color: "#7ab849",
    spotColor: "#7ab849",
    status: false,
  },
  {
    value: "Баклажан",
    label: "Баклажан",
    color: "#735a6f",
    spotColor: "#735a6f",
    status: false,
  },
  {
    value: "Синяк",
    label: "Синяк",
    color: "#41456b",
    spotColor: "#41456b",
    status: false,
  },
  {
    value: "Кефир",
    label: "Кефир",
    color: "#ffffff",
    spotColor: "#ffffff",
    status: false,
  },
  {
    value: "Апельсин",
    label: "Апельсин",
    color: "#ff5c05",
    spotColor: "#ff5c05",
    status: false,
  },
  {
    value: "Желток",
    label: "Желток",
    color: "#d58e22",
    spotColor: "#d58e22",
    status: false,
  },
  {
    value: "Слива",
    label: "Слива",
    color: "#3739c0",
    spotColor: "#3739c0",
    status: false,
  },
  {
    value: "Голубика",
    label: "Голубика",
    color: "#0058b2",
    spotColor: "#0058b2",
    status: false,
  },
];
